services:
  neo4j:
    build: ./neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    environment:
      NEO4J_AUTH: neo4j/AnkerDinoSchiff
    networks:
      - docker-web

  backend:
    build: ./backend
    ports:
      - "8080:8000"
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: AnkerDinoSchiff
    depends_on:
      - neo4j
    networks:
      - docker-web

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - docker-web

volumes:
  neo4j_data:
  neo4j_logs:

networks:
  docker-web:
